version: '3'

services:
  node0:
    container_name: node0
    image: "scalaris/abci"
    ports:
      - "26656-26657:26656-26657"
      - "26670:26660"
    environment:
      - ID=0
      - LOG=${LOG:-cometbft.log}
      - CMTHOME=/scalaris
      - PROXY_APP=kvstore 
      - MONIKER=dockernode
      - CHAIN_ID=evmos_9000-1
    volumes:
      - ./build:/cometbft:Z
      - ./build/scalaris:/usr/local/bin/scalaris:Z
      - ./build/node0:/scalaris:Z
      - ../evmos/build:/cometbft:Z
      - ./start.sh:/usr/bin/start.sh
    entrypoint: "/usr/bin/start.sh"
    command: [
      "node", 
      "--proxy_app=tcp://host.docker.internal:20658", 
      "--scalaris_addr=host.docker.internal:8081",
      "--rpc.laddr=tcp://0.0.0.0:26657",
      "--abci=grpc"
    ]
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    container_name: node1
    image: "scalaris/abci"
    ports:
      - "26659-26660:26656-26657"
      - "26671:26660"
    environment:
      - ID=1
      - LOG=${LOG:-cometbft.log}
      - CMTHOME=/scalaris
      - PROXY_APP=kvstore 
      - MONIKER=dockernode
      - CHAIN_ID=evmos_9000-1
    volumes:
      - ./build:/cometbft:Z
      - ./build/scalaris:/usr/local/bin/scalaris:Z
      - ./build/node1:/scalaris:Z
      - ../evmos/build:/cometbft:Z
      - ./start.sh:/usr/bin/start.sh
    entrypoint: "/usr/bin/start.sh"  
    command: [
      "node", 
      "--proxy_app=tcp://host.docker.internal:21658", 
      "--scalaris_addr=host.docker.internal:8082",
      "--rpc.laddr=tcp://0.0.0.0:26657",
      "--abci=grpc"
    ]
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    container_name: node2
    image: "scalaris/abci"
    environment:
      - ID=2
      - LOG=${LOG:-cometbft.log}
      - CMTHOME=/scalaris
      - PROXY_APP=kvstore 
      - MONIKER=dockernode
      - CHAIN_ID=evmos_9000-1
    ports:
      - "26661-26662:26656-26657"
      - "26672:26660"
    volumes:
      - ./build:/cometbft:Z
      - ./build/scalaris:/usr/local/bin/scalaris:Z
      - ./build/node2:/scalaris:Z
      - ../evmos/build:/cometbft:Z
      - ./start.sh:/usr/bin/start.sh
    entrypoint: "/usr/bin/start.sh"  
    command: [
      "node", 
      "--proxy_app=tcp://host.docker.internal:22658",
      "--scalaris_addr=host.docker.internal:8083",
      "--rpc.laddr=tcp://0.0.0.0:26657",
      "--abci=grpc"
    ]
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    container_name: node3
    image: "scalaris/abci"
    environment:
      - ID=3
      - LOG=${LOG:-cometbft.log}
      - CMTHOME=/scalaris
      - PROXY_APP=kvstore 
      - MONIKER=dockernode
      - CHAIN_ID=evmos_9000-1
    ports:
      - "26663-26664:26656-26657"
      - "26673:26660"
    volumes:
      - ./build:/cometbft:Z
      - ./build/scalaris:/usr/local/bin/scalaris:Z
      - ./build/node3:/scalaris:Z
      - ../evmos/build:/cometbft:Z
      - ./start.sh:/usr/bin/start.sh
    entrypoint: "/usr/bin/start.sh"  
    command: [
      node, 
      "--proxy_app=tcp://host.docker.internal:23658", 
      "--scalaris_addr=host.docker.internal:8084",
      "--rpc.laddr=tcp://0.0.0.0:26657",
      "--abci=grpc"
    ]
    networks:
      localnet:
        ipv4_address: 192.167.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.0.0/16
